version: '3'
services:
    apache:
        build: .docker/apache
        container_name: tp_apache
        ports:
          - 8080:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/tp2609
        depends_on:
          - php

    mysql:
        image: mysql:8
        container_name: tp_mysql
        command: 
          - "--default-authentication-plugin=mysql_native_password"
          - "--skip-grant-tables"
          - "--skip-networking"
        ports:
          - 3306:3306
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: tp2609
            MYSQL_USER: root
            MYSQL_PASSWORD: root

    php:
        build: .docker/php
        container_name: tp_php
        volumes:
          - .:/home/wwwroot/tp2609
        depends_on:
          - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: tp_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8181:80
        links:
            - mysql

    fail2ban:
      image: crazymax/fail2ban:latest
      container_name: fail2ban
      network_mode: "host"
      cap_add:
        - NET_ADMIN
        - NET_RAW
      volumes:
        - "./data:/data"
        - "/var/log:/var/log:ro"
      env_file:
        - "./fail2ban.env"
      restart: always