version: '3.6'
services:
    web:
        build: docker/web
        volumes:
            - ./:/var/www/html
        ports:
            - 8080:80
        depends_on:
            - mysql
    mysql:
        image: 'mysql:5.7'
        ports:
            - '3306:3306'
        environment:
            - MYSQL_DATABASE=esgi1i
            - MYSQL_USER=docker
            - MYSQL_PASSWORD=docker
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
    adminer:
        image: 'adminer:4.7'
        ports:
            - '8081:8080'
