version: "3.7"
services:
  mariadb:
    image: 'mariadb:10.3'
    container_name: mariadb
    volumes:
      - .db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=s3cr3t
      - MYSQL_ROOT_PASSWORD=s3cr3t

  wordpress:
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    ports:
      - "8000:80"
    restart: always
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=docker
      - WORDPRESS_DB_PASSWORD=s3cr3t
      - WORDPRESS_DB_NAME=wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8090:80
    environment:
      - PMA_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=s3cr3t
    depends_on:
      - mariadb

volumes:
  db_data: